#!/bin/env bash

VALID_ARGS=$(getopt -o l:r:gh --long language:,runner,shouldUseGui,help -- "$@")
eval set -- "$VALID_ARGS"

language=""
runner=w3m
shouldUseGui=0

while [ : ]; do
  case "$1" in
    -l | --lang)
        language=$2
        shift 2
        ;;
    -g | --shouldUseGui)
        shouldUseGui=1
        shift
        ;;
    -h | --help)
        echo "Usage: $(basename $0) [-l|--language] <language> [-g|--should-use-gui]"
        exit 0
        ;;
    -r | --runner)
        runner=$2
        shift 2
        ;;
    --) 
        shift; 
        break 
        ;;
    *)
        echo "Invalid option: $1"
        exit 1
        ;;
  esac
done

if [ -z $language]; then
    language=$(fd . ~/Documentos/ArchWiki/ -t d -d 1 | rev | cut -d'/' -f2 | rev | fzf)
    echo $language
fi

path=~/Documentos/ArchWiki/$language
file=$(fd . $path -t f -e ".html" | rev | cut -d'/' -f1 | rev | fzf)

if [[ $shouldUseGui -eq 1 ]]; then
    xdg-open $path/$file&
else
    $runner $path/$file
fi
